### ISSUE TITLE
ioredis support

### ISSUE THREAD

**Issue by directormac** [rhinobase/hono-rate-limiter#22]
Just followed the read me and what was suggested by @MathurAditya724 .

and in reference to #10 

Reproducible snippet
```ts
import Redis from 'ioredis';
import { env } from './env.util';
import { rateLimiter } from 'hono-rate-limiter';
import { generateId } from './crypto.util';

import { type Store } from 'hono-rate-limiter';
import { RedisStore } from 'rate-limit-redis';

const client = new Redis(env.REDIS_URL);

const limiter = rateLimiter({
	windowMs: 15 * 60 * 1000,
	limit: 100,
	// Change the header according to your proxy
	keyGenerator: (c) => c.req.header('X-Forwarded-for') + generateId(20),
	store: new RedisStore({
		sendCommand: (...args: string[]) => client.sendCommand(args)
	}) as unknown as Store // Adding the correct type
});

export { client, limiter };
```

Type error is 
![image](https://github.com/rhinobase/hono-rate-limiter/assets/5866196/2fd50fcd-56db-46ce-88f1-a0afb03b141a)

**Comment by MathurAditya724** [comment]
Hey @directormac, apologies that it took me some time to go through the issue, but upon close inspection, the problem isn't in `hono-rate-limiter` but in `rate-limit-redis` and `ioredis` types. To resolve it you can write `sendCommand: (...args: string[]) => client.sendCommand(args) as Promise<RedisReply>`, because out of the box `ioredis` returns `unknown`.

 You can check the reference here - 
redis-rate-limiter - https://github.com/express-rate-limit/rate-limit-redis/blob/main/source/types.ts#L14
ioredis - https://github.com/redis/ioredis/blob/main/lib/Redis.ts#L423

**Comment by MathurAditya724** [comment]
Yes, I also don't like these semi-typed functions, but this API is neither created nor maintained by me so can't change that. This usage is given here https://github.com/express-rate-limit/rate-limit-redis/tree/main?tab=readme-ov-file#examples, and honesty I went through the code base when I was building `@hono-rate-limiter/redis` package, it's safe you don't have to worry about it.

**Comment by MathurAditya724** [comment]
Yes, I am thinking the same

**Comment by directormac** [comment]
## Solution

```ts
const limiter = rateLimiter({
	windowMs: 15 * 60 * 1000,
	limit: 100,
	keyGenerator: (c) => c.req.header("X-Forwarded-for") + generateId(20),
	store: new RedisStore({
		sendCommand: (...args) => client.sendCommand(args as unknown as Command) as Promise<RedisReply>,
	}) as unknown as Store,
});

export { client, limiter };
```

**Comment by csulit** [comment]
Object literal may only specify known properties, and 'sendCommand' does not exist in type 'Options'.ts(2353)

something change?

**Comment by real2two** [comment]
> Object literal may only specify known properties, and 'sendCommand' does not exist in type 'Options'.ts(2353)
> 
> something change?

+1 The solution above doesn't work for me either. (`Object literal may only specify known properties, and 'sendCommand' does not exist in type 'Options'. ts(2353)`)

**Comment by MathurAditya724** [comment]
I am not sure why you would be putting `1` as a value in `windowMs`, Try putting something like `1 * 60 * 1000` (1 minute). Cause based on your setup the IO might take some time to update the values.

**Comment by MathurAditya724** [comment]
> Object literal may only specify known properties, and 'sendCommand' does not exist in type 'Options'.ts(2353)
> 
> something change?

Can you share a reproduction or your code?

**Comment by melishev** [comment]
I have the same error. Is it currently possible to use this plugin with IORedis?

**Comment by MathurAditya724** [comment]
@melishev, yes you can. If you are facing issues with it, can you create a new github issue with a reproduction? that way I can better help you out
