### ISSUE TITLE
Use JSON instead of text/plain on response

### ISSUE THREAD

**Issue by kevboutin** [rhinobase/hono-rate-limiter#42]
Currently, the response when rate limits are breached:

```
Content-Type: text/plain; charset=UTF-8
Body: Too many requests, please try again later.
```

It would be nice to have the option to use:
```
Content-Type: application/json
Body: { "message": "Too many requests, please try again later." }
```

**Comment by MathurAditya724** [comment]
You can use the `handler` prop to define your custom response. Like how I have done it here - https://github.com/rhinobase/hono-rate-limiter/blob/main/packages/core/src/core.ts#L39-L49

**Comment by kevboutin** [comment]
Confirmed this works:
`handler: (c) => {
      const responseMessage = {
              message: "Too many requests, please try again later.",
              statusCode: 429,
       };
       return c.json(responseMessage);
 }`
